/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/*
* 游戏初始化配置;
*/
import Grid from "./ui/grid";
import Popup from "./ui/Popup";
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        fgui.UIObjectFactory.setExtension("ui://sudoku/grid", Grid);
        fgui.UIObjectFactory.setExtension("ui://sudoku/popup", Popup);
    }
}
GameConfig.init();